version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/myfitnesspal-fetcher:latest@sha256:d5e8ae1400f8908aca3297a2a9b902be0f1940729288a0df7cd16ad0164611ea
    restart: unless-stopped
    environment:
      - RUN_AT_STARTUP=true
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - MFP_COOKIE=${MFP_COOKIE}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}