version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/myfitnesspal-fetcher:latest@sha256:02b1c74d760fcf906e339d1f5150daa52ccc3d0064ec1c5b2242abe82901502d
    restart: unless-stopped
    environment:
      - RUN_AT_STARTUP=true
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - MFP_COOKIE=${MFP_COOKIE}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}