version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/myfitnesspal-fetcher:latest@sha256:6d53ee6de18d2cea4e80ef7118e185adccef78ed988821e245bb85fec90da99c
    restart: unless-stopped
    environment:
      - RUN_AT_STARTUP=true
      - GCP_CREDENTIALS=${GCP_CREDENTIALS}
      - MFP_COOKIE=${MFP_COOKIE}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}